Update documentation to incorporate ITB
meaningfy-ws/semic-styleguide-rdf-validator pull request #2
Opened 2024-02-01 15:03 UTC by schivmeister

Please view the markdown using your editor of choice or https://dillinger.io/ (here however line breaks appear to be odd).

2024-02-01 15:29 UTC, csnyulas approved these changes
Looks really nice and comprehensive.

2024-02-02 11:47 UTC, Dragos0000 requested changes
readme for SEMIC Conformance Test Suite for OWL and ShaCL should be different from 
ITB SEMIC SHACL VALIDATOR. the readme that will appear on github should be the ITB SEMIC SHACL VALIDATOR please take inspiration from https://github.com/meaningfy-ws/model2owl-validator. This readme is describing the service that will appear on ITB

2024-02-02 12:02 UTC, schivmeister commented
> readme for SEMIC Conformance Test Suite for OWL and ShaCL should be different from ITB SEMIC SHACL VALIDATOR. the readme that will appear on github should be the ITB SEMIC SHACL VALIDATOR please take inspiration from https://github.com/meaningfy-ws/model2owl-validator. This readme is describing the service that will appear on ITB

Agreed with Dragos to clearly demarcate the two components with two sections. That is, until Costas has a different opinion.

2024-02-02 12:44 UTC, Dragos0000 approved these changes

2024-02-02 12:46 UTC, merged