ITB-SEMIC customization
meaningfy-ws/semic-styleguide-rdf-validator pull request #7
Opened 2024-02-06 21:13 UTC by schivmeister

- Mission-specific documentation
- Separate OWL and SHACL validation (combined does not make sense now and has oddities, but can be done at some point)
- ePO example data (no results for now, use the simpler non-ePO example for testing)
- ITB/Java-specific SHACL-SPARQL fixes
- Latest snapshot of shapes for the (micro)service

2024-02-07 13:44 UTC, csnyulas approved these changes
Looks fine.

2024-02-08 15:01 UTC, Dragos0000 requested changes

2024-02-08 15:01 UTC, Dragos0000 commented on resources/config.properties
> +validator.completeTypeOptionLabel.owl.basic = Validated with basic configuration
you have duplicate configuration. validator.completeTypeOptionLabel.owl.basic  X 2 . should be one and one 
validator.completeTypeOptionLabel.owl.basic
validator.completeTypeOptionLabel.shacl.basic
validator.completeTypeOptionLabel.owl.advanced
validator.completeTypeOptionLabel.shacl.advanced
Change the wording on this labels taking in consideration that you have 2 different validation SHACL and OWL so you can go with Validated OWL with basic configuration perhaps.

Always test the validator locally with all available options.

2024-02-08 15:09 UTC, schivmeister commented on resources/config.properties
> +validator.completeTypeOptionLabel.owl.basic = Validated with basic configuration
@Dragos0000 good catch, thanks. all options were tested locally but this one was sneaky, likely because it had no effect

2024-02-08 15:13 UTC, Dragos0000 approved these changes

2024-02-08 15:48 UTC, schivmeister commented
Also made some How-To wording improvements according to @Dragos0000's suggestions.

2024-02-08 15:48 UTC, merged